In [47]:
import csv
import pandas as pd
business_coord = pd.read_csv("상권_좌표.csv")
b_s_coord=business_coord 
b_s_coord[b_s_coord['상권_구분_코드']=='A']

,상권_구분_코드,상권_코드,상권_코드_명,상권_구분_코드_명,x,y,x1,y1,WGS84_x,WGS84_y,WGS84_x1,WGS84_y1
70,A,1000334,삼양로93길,골목상권,201480.00,460016.74,201412.69,459892.51,127.016769,37.639767,127.016006,37.638648
71,A,1000354,덕릉로60길,골목상권,203607.69,459892.88,203681.18,459488.76,127.040875,37.638645,127.041706,37.635004
72,A,1000355,도당로13가길,골목상권,203193.88,462986.66,203193.88,462986.66,127.036200,37.666521,127.036200,37.666521
73,A,1000356,도당로13바길,골목상권,203267.48,463121.57,202840.58,462986.39,127.037035,37.667736,127.032196,37.666520
74,A,1000357,도당로19길,골목상권,203611.30,463181.86,203358.00,463264.55,127.040932,37.668278,127.038061,37.669024
...,...,...,...,...,...,...,...,...,...,...,...,...
1484,A,1000380,동일로192길,골목상권,206882.09,458673.89,206542.84,458460.52,127.077962,37.627643,127.074117,37.625723
1485,A,1000381,동일로242길,골목상권,204989.69,464047.60,205301.29,463808.97,127.056561,37.676072,127.060092,37.673920
1486,A,1000071,이태원로54길,골목상권,200189.02,448464.88,200138.64,448759.61,127.002139,37.535687,127.001569,37.538342
1487,A,1000072,장문로45길,골목상권,200029.21,447819.09,200097.65,447472.17,127.000330,37.529868,127.001105,37.526742
1488,A,1000073,청파로47길,골목상권,197082.82,449569.57,197222.40,449383.42,126.966990,37.545635,126.968570,37.543958

In [2]:
#필요한 행만 추출, 구글 좌표계와 일치하는 위도, 경도 추출.
b_s_coord = b_s_coord[['상권_구분_코드','상권_코드','상권_코드_명','상권_구분_코드_명','WGS84_x','WGS84_y','WGS84_x1','WGS84_y1']]
b_s_coord['상권_구분_코드_명'].unique() #'전통시장', '관광특구', '골목상권', '발달상권''

array(['전통시장', '관광특구', '골목상권', '발달상권'], dtype=object)

In [40]:
b_s_coord.head()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [4]:
#데이터가 많아 상권 별로 populartime data를 크롤링한다. 
market = b_s_coord[b_s_coord['상권_구분_코드_명']=='전통시장']
tour = b_s_coord[b_s_coord['상권_구분_코드_명']=='관광특구']
local = b_s_coord[b_s_coord['상권_구분_코드_명']=='골목상권']
active =b_s_coord[b_s_coord['상권_구분_코드_명']=='발달상권']

In [5]:
import populartimes
from datetime import datetime
now = datetime.now()
date = ('%s-%s-%s' % ( now.year, now.month, now.day))
hour = int(now.hour)

day_of_week_list = ["Monday","Tuesday","Wednesday","Thurday","Friday","Saturday","Sunday"]
time_list = ["00:00:00","01:00:00","02:00:00","03:00:00","04:00:00","05:00:00","06:00:00","07:00:00","08:00:00","09:00:00","10:00:00","11:00:00","12:00:00","13:00:00","14:00:00","15:00:00","16:00:00","17:00:00","18:00:00","19:00:00","20:00:00","21:00:00","22:00:00","23:00:00","24:00:00"]
list_ = []
list1 = []
list2 = []
list3 = []

key = "AIzaSyBrYxfBUdl1jcJGUNjX9JSHHh3J82C3zBE"
types = ["store","subway_station","restaurant","bakery","cafe","aquarium","liquor_store","art_gallery","bar","meal_delevery","meal_takeaway","movie_theater","museum","convenience_store","shopping_mall","supermarket","grocery_or_supermarket","university","jewelry_store","hair_care"]
def getData(x,y,x1,y1):
    data =populartimes.get(key, types, (x,y),(x1,y1))
    return data

def crawling_populartime(data, week=1):
    for i in range(len(data)):
        business_distinct_code = data.iloc[i]['상권_구분_코드']
        business_area_code = str(data.iloc[i]['상권_코드'])
        business_area_name = data.iloc[i]['상권_코드_명']
        x = data.iloc[i]['WGS84_y']
        y = data.iloc[i]['WGS84_x']
        x1 = data.iloc[i]['WGS84_y1']
        y1 = data.iloc[i]['WGS84_x1']

        crawl_data = getData(x,y,x1,y1)

        for i in range(len(crawl_data)):
            type_len = len(crawl_data[i]['types'])
            id_ = crawl_data[i]["id"]
            store_name = crawl_data[i]["name"]
            address = crawl_data[i]["address"]
            lat = float(crawl_data[i]["coordinates"]['lat'])
            lng = float(crawl_data[i]["coordinates"]['lng'])
            types =crawl_data[i]["types"]
            if 'rating' in crawl_data[i]:
                rating = float(crawl_data[i]["rating"])
            else:
                rating = 0
            if 'rating_n' in crawl_data[i]:
                rating_n = int(crawl_data[i]["rating_n"])
            else:
                rating_n = 0
            if "time_spent" in crawl_data[i]:
                timespent_min = int(crawl_data[i]["time_spent"][0])
                timespent_max = int(crawl_data[i]["time_spent"][1])
            else:
                timespent_min = 0
                timespent_max = 0
            if "current_popularity" in crawl_data[i]:
                current_popular = crawl_data[i]['current_popularity']
            else:
                current_popular = 0

            for i in range(type_len):
                t = [id_,date,week,business_distinct_code, business_area_code,business_area_name,store_name, address,lng,lat,types[i]]
                list_.append(t)
            for i in range(7):
                dayofweek = day_of_week_list[i]
                for j in range(24):
                    hour = time_list[j]
                    t1 = [id_,date,week,dayofweek,hour,crawl_data[0]["populartimes"][i]["data"][j],business_distinct_code,business_area_code]
                    list1.append(t1)
            t2 = [id_,date,week,business_distinct_code, business_area_code,rating,rating_n,timespent_min,timespent_max]
            t3 = [id_,date,week,hour,store_name, current_popular, business_distinct_code, business_area_code]
            list2.append(t2)
            list3.append(t3)

In [37]:
import csv
#table 별로 구분해서 저장한다. 각 table 마다의 schema 파일이 존재한다.
f = open('store.csv','w', encoding= 'utf-8')
f1 = open('populartime.csv','w', encoding ='utf-8')
f2 = open('store_rating.csv','w', encoding ='utf-8')
f3 = open('current_populartiy.csv','w', encoding ='utf-8')

f_header=['id_','date','week','business_distinct_code', 'business_area_code','business_area_name','store_name', 'address','lng','lat','type']
f1_header=['id_','date','week','dayofweek','hour','popular_data','business_distinct_code','business_area_code']
f2_header=['id_','date','week','business_distinct_code','business_area_code','rating','rating_n','timespent_min','timespent_max']
f3_header=['id_','date','week','hour','store_name','current_popular','business_distinct_code','business_area_code']

f_ = open('store.csv','a',encoding= 'utf-8')
f1_ = open('populartime.csv','a',encoding= 'utf-8')
f2_ = open('store_rating.csv','a',encoding= 'utf-8')
f3_ = open('current_populartiy.csv','a',encoding= 'utf-8')

def write_csv(f,list,header):
    f
    wr = csv.writer(f)
    wr.writerow(header)
    for i in range(len(list)):
        insert_row =list[i]
        wr.writerow(insert_row)
    f.close()
write_csv(f,list_,f_header)
write_csv(f1,list1,f1_header)
write_csv(f2,list2,f2_header)
write_csv(f3,list3,f3_header)
def add_csv(f_, list):
    f_
    wr = csv.writer(f_)
    for i in range(len(list)):
        insert_row =list[i]
        wr.writerow(insert_row)
    f_.close()

In [49]:
data=[market, tour, local, active]
list_all = [list_,list1,list2,list3]
#header = [f_header,f1_header,f2_header,f3_header]

for i in range(2,3):
    crawling_populartime(data[i])

WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost

In [51]:
f_ = open('store.csv','a',encoding= 'utf-8')
add_csv(f_,list_)
f1_ = open('populartime.csv','a',encoding= 'utf-8')
add_csv(f1_,list1)
f2_ = open('store_rating.csv','a',encoding= 'utf-8')
add_csv(f2_,list2)
f3_ = open('current_populartiy.csv','a',encoding= 'utf-8')
add_csv(f3_,list3)

In [15]:
from google.cloud import bigquery
#bigquery streaming data
def insert_to_bigquery(dataset_id,table_id, rows_list):
    client = bigquery.Client(project = 'bigquery-259414')
    dataset_id = dataset_id 
    table_id = table_id
    table_ref = client.dataset(dataset_id).table(table_id)
    table = client.get_table(table_ref)
    rows_to_insert = rows_list
    
    errors = client.insert_rows(table, rows_to_insert)
    assert errors == []

In [50]:
a_list_ = list_
a_list1 = list1
a_list2 = list2
a_list3 = list3